os:
  - linux
language: generic
sudo: required
dist: xenial

services:
  - docker

addons:
    snaps:
      - name: aws-cli
        confinement: classic # or devmode
        channel: latest/edge

install:
  - make --version
  - make docker_build

script:
  - docker image ls
  - make swift_test_with_coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -f .build/x86_64-unknown-linux/debug/codecov/lcov.info